/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vidyalaya.View.Dashboard.Teacher;

import java.awt.GridLayout;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

import vidyalaya.Utils.Utils;

import raven.glasspanepopup.GlassPanePopup;

import vidyalaya.Model.MaterialData;
import vidyalaya.Model.ModuleData;

import vidyalaya.DAO.ModuleDAO.ModuleDAO;
import vidyalaya.DAO.ModuleDAO.ModuleDAOImplementation;

import vidyalaya.Components.MaterialPopup;
import vidyalaya.Components.MaterialCard;
import vidyalaya.Components.Modals.CreateMaterialForm;

/**
 *
 * @author trish
 */
public class MaterialScreen extends javax.swing.JFrame {

    int moduleCode;

    /**
     * Creates new form MaterialScreen
     *
     * @param module
     */
    public MaterialScreen(ModuleData module) {
        initComponents();
        GlassPanePopup.install(this);
        this.moduleCode = module.getCode();
        initializeGrid();

        String courseName = module.getName();
        courseTitle.setText(courseName);

        setTitle("Materials - " + courseName);
        setSize(1400, 954);
        setLocationRelativeTo(null);
        setResizable(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Utils.setFrameIcon(this, "/vidyalaya/Assets/logo.png");

        Utils.setCustomFont(courseTitle, 23f);
        Utils.setCustomFont(createMaterialBtn, 17f);

    }

    private void initializeGrid() {
        try {
            ModuleDAO moduleDAO = new ModuleDAOImplementation();
            List<MaterialData> materials = moduleDAO.getAllMaterials(moduleCode);
            materials.forEach(x -> addGrid(x));
            var grid = new GridLayout(0, 1);
            grid.setHgap(10);
            grid.setVgap(10);
            pnlMaterials.setLayout(grid);
        } catch (Exception ex) {
            Logger.getLogger(MaterialScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void addGrid(MaterialData data) {
        var temp = new MaterialCard(data,
                () -> {
                    GlassPanePopup.showPopup(new MaterialPopup(data));
                },
                () -> {
                    System.out.println("Edit: " + data.getId());
                },
                () -> {
                    try {
                        ModuleDAO moduleDAO = new ModuleDAOImplementation();
                        int result = Utils.confirm(this, "Are you sure you want to delete this material?");
                        if (result == JOptionPane.YES_OPTION) {
                            moduleDAO.deleteMaterial(data.getId());

                            vidyalaya.View.Dashboard.Teacher.MyCoursesScreen coursesView = new vidyalaya.View.Dashboard.Teacher.MyCoursesScreen();
                            vidyalaya.Controller.Courses.Teacher.MyCoursesController coursesController = new vidyalaya.Controller.Courses.Teacher.MyCoursesController(coursesView);
                            Utils.closeAllFrames();
                            coursesController.open();
                            Utils.success("Material deleted successfully!");
                        }
                    } catch (Exception ex) {
                        Utils.error(ex.getMessage());
                    }
                });
        pnlMaterials.add(temp);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        pnlMaterials = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        courseTitle = new javax.swing.JLabel();
        createCourse = new javax.swing.JPanel();
        createMaterialBtn = new javax.swing.JLabel();
        iconUsers1 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        pnlMaterials.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlMaterialsLayout = new javax.swing.GroupLayout(pnlMaterials);
        pnlMaterials.setLayout(pnlMaterialsLayout);
        pnlMaterialsLayout.setHorizontalGroup(
            pnlMaterialsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlMaterialsLayout.setVerticalGroup(
            pnlMaterialsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 709, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        courseTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        courseTitle.setText("Object Oriented Programming");

        createCourse.setBackground(new java.awt.Color(24, 97, 191));
        createCourse.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        createCourse.setForeground(new java.awt.Color(255, 255, 255));
        createCourse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createCourse.setPreferredSize(new java.awt.Dimension(100, 52));

        createMaterialBtn.setForeground(new java.awt.Color(255, 255, 255));
        createMaterialBtn.setText("Create Material");
        createMaterialBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createMaterialBtnMouseClicked(evt);
            }
        });

        iconUsers1.setBackground(new java.awt.Color(24, 97, 191));
        iconUsers1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vidyalaya/Assets/icons/Create.png"))); // NOI18N

        javax.swing.GroupLayout createCourseLayout = new javax.swing.GroupLayout(createCourse);
        createCourse.setLayout(createCourseLayout);
        createCourseLayout.setHorizontalGroup(
            createCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createCourseLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(iconUsers1)
                .addGap(18, 18, 18)
                .addComponent(createMaterialBtn)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        createCourseLayout.setVerticalGroup(
            createCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iconUsers1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(createMaterialBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(courseTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 801, Short.MAX_VALUE)
                .addComponent(createCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(createCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(courseTitle))
        );

        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vidyalaya/Assets/icons/Left.png"))); // NOI18N
        backButton.setBorder(null);
        backButton.setBorderPainted(false);
        backButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backButton.setFocusPainted(false);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlMaterials, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(pnlMaterials, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void createMaterialBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createMaterialBtnMouseClicked
        // TODO add your handling code here:
        new CreateMaterialForm(this.moduleCode).setVisible(true);
    }//GEN-LAST:event_createMaterialBtnMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel courseTitle;
    private javax.swing.JPanel createCourse;
    private javax.swing.JLabel createMaterialBtn;
    private javax.swing.JLabel iconUsers1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pnlMaterials;
    // End of variables declaration//GEN-END:variables
}
