/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vidyalaya.View;

import java.awt.Font;
import java.io.File;
import vidyalaya.Utils.DMSans;

/**
 *
 * @author trishan9
 */
public class CreateAdmin extends javax.swing.JFrame {

    /**
     * Creates new form CreateAdmin
     */
    public CreateAdmin() {
        initComponents();
        
        // Custom Font Setting 
        DMSans dmSans = new DMSans();
        jLabelHead.setFont(dmSans.getFont());
        createMessage.setFont(dmSans.getFont());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlNav = new javax.swing.JPanel();
        jLabelHead = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnlCenter = new javax.swing.JPanel();
        pnlCenterLeft = new javax.swing.JPanel();
        pnlCenterMid = new javax.swing.JPanel();
        pnlMessage = new javax.swing.JPanel();
        createMessage = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pnlForm = new javax.swing.JPanel();
        pnlCenterRight = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlNav.setBackground(new java.awt.Color(255, 255, 255));
        pnlNav.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(222, 222, 222), 2));
        pnlNav.setPreferredSize(new java.awt.Dimension(835, 80));

        jLabelHead.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabelHead.setForeground(new java.awt.Color(0, 162, 100));
        jLabelHead.setText("Vidyalaya");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vidyalaya/Assets/vidyalaya-logo.png"))); // NOI18N

        javax.swing.GroupLayout pnlNavLayout = new javax.swing.GroupLayout(pnlNav);
        pnlNav.setLayout(pnlNavLayout);
        pnlNavLayout.setHorizontalGroup(
            pnlNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelHead)
                .addContainerGap(1274, Short.MAX_VALUE))
        );
        pnlNavLayout.setVerticalGroup(
            pnlNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNavLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabelHead)
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNavLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(pnlNav, java.awt.BorderLayout.PAGE_START);

        pnlCenter.setBackground(new java.awt.Color(255, 255, 255));
        pnlCenter.setPreferredSize(new java.awt.Dimension(0, 800));
        pnlCenter.setLayout(new java.awt.GridLayout(1, 3, 400, 0));

        pnlCenterLeft.setMaximumSize(new java.awt.Dimension(100, 100));
        pnlCenterLeft.setPreferredSize(new java.awt.Dimension(20, 362));

        javax.swing.GroupLayout pnlCenterLeftLayout = new javax.swing.GroupLayout(pnlCenterLeft);
        pnlCenterLeft.setLayout(pnlCenterLeftLayout);
        pnlCenterLeftLayout.setHorizontalGroup(
            pnlCenterLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        pnlCenterLeftLayout.setVerticalGroup(
            pnlCenterLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 362, Short.MAX_VALUE)
        );

        pnlCenter.add(pnlCenterLeft);

        pnlCenterMid.setBackground(new java.awt.Color(255, 255, 255));
        pnlCenterMid.setLayout(new java.awt.BorderLayout());

        pnlMessage.setBackground(new java.awt.Color(255, 255, 255));
        pnlMessage.setPreferredSize(new java.awt.Dimension(278, 250));
        pnlMessage.setLayout(new java.awt.BorderLayout());

        createMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        createMessage.setText("Create an admin account");
        pnlMessage.add(createMessage, java.awt.BorderLayout.CENTER);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vidyalaya/Assets/vidyalaya-large.png"))); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(100, 120));
        jLabel3.setVerifyInputWhenFocusTarget(false);
        pnlMessage.add(jLabel3, java.awt.BorderLayout.PAGE_START);

        pnlCenterMid.add(pnlMessage, java.awt.BorderLayout.PAGE_START);

        pnlForm.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlFormLayout = new javax.swing.GroupLayout(pnlForm);
        pnlForm.setLayout(pnlFormLayout);
        pnlFormLayout.setHorizontalGroup(
            pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        pnlFormLayout.setVerticalGroup(
            pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlCenterMid.add(pnlForm, java.awt.BorderLayout.CENTER);

        pnlCenter.add(pnlCenterMid);

        javax.swing.GroupLayout pnlCenterRightLayout = new javax.swing.GroupLayout(pnlCenterRight);
        pnlCenterRight.setLayout(pnlCenterRightLayout);
        pnlCenterRightLayout.setHorizontalGroup(
            pnlCenterRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        pnlCenterRightLayout.setVerticalGroup(
            pnlCenterRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 362, Short.MAX_VALUE)
        );

        pnlCenter.add(pnlCenterRight);

        getContentPane().add(pnlCenter, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel createMessage;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelHead;
    private javax.swing.JPanel pnlCenter;
    private javax.swing.JPanel pnlCenterLeft;
    private javax.swing.JPanel pnlCenterMid;
    private javax.swing.JPanel pnlCenterRight;
    private javax.swing.JPanel pnlForm;
    private javax.swing.JPanel pnlMessage;
    private javax.swing.JPanel pnlNav;
    // End of variables declaration//GEN-END:variables
}
