/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vidyalaya.Components;

import vidyalaya.Model.ModuleData;

import vidyalaya.Utils.CallbackFn;
import vidyalaya.Utils.Utils;

/**
 *
 * @author trish
 */
public class CourseCardUser extends javax.swing.JPanel {

    CallbackFn onClick;

    /**
     * Creates new form CourseCardUser
     *
     * @param module
     * @param userType
     * @param onClick
     */
    public CourseCardUser(ModuleData module, String userType, CallbackFn onClick) {
        initComponents();
        courseTitle.setText(module.getName());
        courseCode.setText(String.valueOf(module.getCode()));
        this.onClick = onClick;

        Utils.setCustomFont(courseTitleHeader, 15f);
        Utils.setCustomFont(courseTitle, 17f);
        Utils.setCustomFont(courseCodeHeader, 15f);
        Utils.setCustomFont(courseCode, 17f);
        Utils.setCustomFont(accessMaterialsBtn, 17f);
        
        if(userType.equals("TEACHER")){
            accessMaterialsBtn.setText("Manage Materials");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCourse = new javax.swing.JPanel();
        courseTitleHeader = new javax.swing.JLabel();
        courseTitle = new javax.swing.JLabel();
        courseCodeHeader = new javax.swing.JLabel();
        courseCode = new javax.swing.JLabel();
        accessMaterialsBtn = new javax.swing.JButton();

        pnlCourse.setBackground(new java.awt.Color(255, 255, 255));
        pnlCourse.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(222, 222, 222)));

        courseTitleHeader.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        courseTitleHeader.setForeground(new java.awt.Color(130, 130, 130));
        courseTitleHeader.setText("Course Title");

        courseTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        courseTitle.setText("Object Oriented Programming");

        courseCodeHeader.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        courseCodeHeader.setForeground(new java.awt.Color(130, 130, 130));
        courseCodeHeader.setText("Course Code");

        courseCode.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        courseCode.setText("200");

        accessMaterialsBtn.setBackground(new java.awt.Color(193, 241, 212));
        accessMaterialsBtn.setText("Access Materials");
        accessMaterialsBtn.setBorder(null);
        accessMaterialsBtn.setBorderPainted(false);
        accessMaterialsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        accessMaterialsBtn.setFocusPainted(false);
        accessMaterialsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onMaterialsBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCourseLayout = new javax.swing.GroupLayout(pnlCourse);
        pnlCourse.setLayout(pnlCourseLayout);
        pnlCourseLayout.setHorizontalGroup(
            pnlCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCourseLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(pnlCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(courseTitle)
                    .addComponent(courseTitleHeader))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                .addGroup(pnlCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCourseLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(courseCode))
                    .addComponent(courseCodeHeader))
                .addGap(277, 277, 277)
                .addComponent(accessMaterialsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlCourseLayout.setVerticalGroup(
            pnlCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCourseLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnlCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pnlCourseLayout.createSequentialGroup()
                            .addComponent(courseCodeHeader)
                            .addGap(10, 10, 10)
                            .addComponent(courseCode))
                        .addGroup(pnlCourseLayout.createSequentialGroup()
                            .addComponent(courseTitleHeader)
                            .addGap(10, 10, 10)
                            .addComponent(courseTitle)))
                    .addComponent(accessMaterialsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void onMaterialsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onMaterialsBtnActionPerformed
        // TODO add your handling code here:
        onClick.onTrigger();
    }//GEN-LAST:event_onMaterialsBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accessMaterialsBtn;
    private javax.swing.JLabel courseCode;
    private javax.swing.JLabel courseCodeHeader;
    private javax.swing.JLabel courseTitle;
    private javax.swing.JLabel courseTitleHeader;
    private javax.swing.JPanel pnlCourse;
    // End of variables declaration//GEN-END:variables
}
