/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vidyalaya.Components;

import java.util.logging.Level;
import java.util.logging.Logger;

import vidyalaya.Utils.Utils;

import vidyalaya.DAO.AttendanceDAO.AttendanceDAOImplementation;
import vidyalaya.DAO.ModuleDAO.ModuleDAOImplementation;

import vidyalaya.Model.ModuleData;

/**
 *
 * @author trish
 */
public class CourseAttendanceCard extends javax.swing.JPanel {

    /**
     * Creates new form CourseAttendanceCard
     *
     * @param studentId
     * @param courseId
     */
    public CourseAttendanceCard(int studentId, int courseId) {
        try {
            initComponents();

            Utils.setCustomFont(courseName, 18f);
            Utils.setCustomFont(coursePresent, 14f);
            Utils.setCustomFont(courseAbsent, 14f);

            ModuleDAOImplementation moduleDAO = new ModuleDAOImplementation();
            ModuleData course = moduleDAO.getModuleByCode(courseId);
            courseName.setText(course.getName());

            AttendanceDAOImplementation attendanceDAO = new AttendanceDAOImplementation();
            int totalTaughtDays = attendanceDAO.getCourseTaughtDays(courseId);
            int totalAbsentDays = attendanceDAO.getCourseAbsentDays(studentId, courseId);
            int totalPresentDays = totalTaughtDays - totalAbsentDays;

            coursePresent.setText("Present: " + totalPresentDays);
            courseAbsent.setText("Absent: " + totalAbsentDays);
        } catch (Exception ex) {
            Logger.getLogger(CourseAttendanceCard.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        courseAttendance = new javax.swing.JPanel();
        courseName = new javax.swing.JLabel();
        coursePresent = new javax.swing.JLabel();
        courseAbsent = new javax.swing.JLabel();

        courseAttendance.setBackground(new java.awt.Color(207, 64, 127));
        courseAttendance.setForeground(new java.awt.Color(255, 255, 255));

        courseName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        courseName.setForeground(new java.awt.Color(255, 255, 255));
        courseName.setText("Object Oriented Programming");

        coursePresent.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        coursePresent.setForeground(new java.awt.Color(255, 255, 255));
        coursePresent.setText("Present: 20");

        courseAbsent.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        courseAbsent.setForeground(new java.awt.Color(255, 255, 255));
        courseAbsent.setText("Absent: 90");

        javax.swing.GroupLayout courseAttendanceLayout = new javax.swing.GroupLayout(courseAttendance);
        courseAttendance.setLayout(courseAttendanceLayout);
        courseAttendanceLayout.setHorizontalGroup(
            courseAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(courseAttendanceLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(courseAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(courseAttendanceLayout.createSequentialGroup()
                        .addComponent(courseName, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(51, Short.MAX_VALUE))
                    .addGroup(courseAttendanceLayout.createSequentialGroup()
                        .addComponent(coursePresent)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(courseAbsent)
                        .addGap(14, 14, 14))))
        );
        courseAttendanceLayout.setVerticalGroup(
            courseAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, courseAttendanceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(courseName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(courseAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coursePresent)
                    .addComponent(courseAbsent))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(courseAttendance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(courseAttendance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel courseAbsent;
    private javax.swing.JPanel courseAttendance;
    private javax.swing.JLabel courseName;
    private javax.swing.JLabel coursePresent;
    // End of variables declaration//GEN-END:variables
}
