/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vidyalaya.Components;

import vidyalaya.Utils.CallbackFn;
import vidyalaya.Utils.Utils;

import vidyalaya.Model.MaterialData;

/**
 *
 * @author trish
 */
public class MaterialCard extends javax.swing.JPanel {

    CallbackFn onViewClick, onEditClick, onDeleteClick;

    /**
     * Creates new form MaterialCard
     *
     * @param material
     * @param onViewClick
     * @param onEditClick
     * @param onDeleteClick
     */
    public MaterialCard(MaterialData material, CallbackFn onViewClick, CallbackFn onEditClick, CallbackFn onDeleteClick) {
        initComponents();
        materialTitle.setText(material.getMaterialTitle());
        this.onEditClick = onEditClick;
        this.onDeleteClick = onDeleteClick;
        this.onViewClick = onViewClick;

        Utils.setCustomFont(materialTitle, 17f);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRoutine = new javax.swing.JPanel();
        materialTitle = new javax.swing.JLabel();
        editButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        viewButton = new javax.swing.JButton();

        pnlRoutine.setBackground(new java.awt.Color(255, 255, 255));
        pnlRoutine.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(222, 222, 222)));

        materialTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        materialTitle.setText("Introduction to OOP");

        editButton.setBackground(new java.awt.Color(193, 241, 212));
        editButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vidyalaya/Assets/icons/Edit.png"))); // NOI18N
        editButton.setBorder(null);
        editButton.setBorderPainted(false);
        editButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editButton.setFocusPainted(false);
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onEditButtonActionPerformed(evt);
            }
        });

        deleteButton.setBackground(new java.awt.Color(234, 186, 184));
        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vidyalaya/Assets/icons/Delete.png"))); // NOI18N
        deleteButton.setBorder(null);
        deleteButton.setBorderPainted(false);
        deleteButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteButton.setFocusPainted(false);
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onDeleteButtonActionPerformed(evt);
            }
        });

        viewButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vidyalaya/Assets/icons/View.png"))); // NOI18N
        viewButton.setBorder(null);
        viewButton.setBorderPainted(false);
        viewButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewButton.setFocusPainted(false);
        viewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onViewButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRoutineLayout = new javax.swing.GroupLayout(pnlRoutine);
        pnlRoutine.setLayout(pnlRoutineLayout);
        pnlRoutineLayout.setHorizontalGroup(
            pnlRoutineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRoutineLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(materialTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 745, Short.MAX_VALUE)
                .addComponent(viewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlRoutineLayout.setVerticalGroup(
            pnlRoutineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRoutineLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlRoutineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(viewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
            .addGroup(pnlRoutineLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(materialTitle)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRoutine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlRoutine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void onEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onEditButtonActionPerformed
        // TODO add your handling code here:
        onEditClick.onTrigger();
    }//GEN-LAST:event_onEditButtonActionPerformed

    private void onDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onDeleteButtonActionPerformed
        // TODO add your handling code here:
        onDeleteClick.onTrigger();
    }//GEN-LAST:event_onDeleteButtonActionPerformed

    private void onViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onViewButtonActionPerformed
        // TODO add your handling code here:
        onViewClick.onTrigger();
    }//GEN-LAST:event_onViewButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel materialTitle;
    private javax.swing.JPanel pnlRoutine;
    private javax.swing.JButton viewButton;
    // End of variables declaration//GEN-END:variables
}
