/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vidyalaya.Components;

import java.util.logging.Level;
import java.util.logging.Logger;

import vidyalaya.Utils.CallbackFn;
import vidyalaya.Utils.Utils;

import vidyalaya.Model.NoticeData;

/**
 *
 * @author trish
 */
public class NoticeCard extends javax.swing.JPanel {

    CallbackFn onSeeMoreClick, onEditClick, onDeleteClick;

    /**
     * Creates new form NoticeCard
     *
     * @param notice
     * @param onSeeMoreClick
     * @param onEditClick
     * @param onDeleteClick
     */
    public NoticeCard(NoticeData notice, CallbackFn onSeeMoreClick, CallbackFn onEditClick, CallbackFn onDeleteClick) {
        try {
            initComponents();
            noticeTitle.setText(notice.getTitle());
            noticeContent.setText(Utils.truncateString(notice.getContent()));
            noticeDate.setText(Utils.parseTimestampAndCalculateDifference(notice.getCreatedAt()));
            effectiveDate.setText(notice.getEffectiveDate());
            this.onEditClick = onEditClick;
            this.onDeleteClick = onDeleteClick;
            this.onSeeMoreClick = onSeeMoreClick;

            Utils.setCustomFont(noticeTitle, 15f);
            Utils.setCustomFont(noticeContent, 17f);
            Utils.setCustomFont(noticeDate, 15f);
            Utils.setCustomFont(noticeTitle1, 15f);
            Utils.setCustomFont(effectiveDate, 15f);
            Utils.setCustomFont(seeMoreBtn, 14f);

            Utils.handleButtonVisibility(notice.getContent(), seeMoreBtn);
        } catch (Exception ex) {
            Logger.getLogger(NoticeCard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRoutine = new javax.swing.JPanel();
        noticeTitle = new javax.swing.JLabel();
        noticeContent = new javax.swing.JLabel();
        editButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        seeMoreBtn = new javax.swing.JButton();
        noticeDate = new javax.swing.JLabel();
        noticeTitle1 = new javax.swing.JLabel();
        effectiveDate = new javax.swing.JLabel();

        pnlRoutine.setBackground(new java.awt.Color(255, 255, 255));
        pnlRoutine.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(222, 222, 222)));

        noticeTitle.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        noticeTitle.setForeground(new java.awt.Color(130, 130, 130));
        noticeTitle.setText("Tech X 2024 Volunteer");

        noticeContent.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        noticeContent.setText("Dear students, join Tech-ex 2024.....");

        editButton.setBackground(new java.awt.Color(193, 241, 212));
        editButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vidyalaya/Assets/icons/Edit.png"))); // NOI18N
        editButton.setBorder(null);
        editButton.setBorderPainted(false);
        editButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editButton.setFocusPainted(false);
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onEditButtonActionPerformed(evt);
            }
        });

        deleteButton.setBackground(new java.awt.Color(234, 186, 184));
        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vidyalaya/Assets/icons/Delete.png"))); // NOI18N
        deleteButton.setBorder(null);
        deleteButton.setBorderPainted(false);
        deleteButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteButton.setFocusPainted(false);
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onDeleteButtonActionPerformed(evt);
            }
        });

        seeMoreBtn.setText("See more");
        seeMoreBtn.setBorder(null);
        seeMoreBtn.setBorderPainted(false);
        seeMoreBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        seeMoreBtn.setFocusPainted(false);
        seeMoreBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onSeeMoreBtnActionPerformed(evt);
            }
        });

        noticeDate.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        noticeDate.setForeground(new java.awt.Color(130, 130, 130));
        noticeDate.setText("8 days ago");

        noticeTitle1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        noticeTitle1.setForeground(new java.awt.Color(130, 130, 130));
        noticeTitle1.setText("Effective: ");

        effectiveDate.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        effectiveDate.setForeground(new java.awt.Color(130, 130, 130));
        effectiveDate.setText("04/08/2024");

        javax.swing.GroupLayout pnlRoutineLayout = new javax.swing.GroupLayout(pnlRoutine);
        pnlRoutine.setLayout(pnlRoutineLayout);
        pnlRoutineLayout.setHorizontalGroup(
            pnlRoutineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRoutineLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(pnlRoutineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRoutineLayout.createSequentialGroup()
                        .addComponent(noticeDate)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlRoutineLayout.createSequentialGroup()
                        .addGroup(pnlRoutineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlRoutineLayout.createSequentialGroup()
                                .addComponent(noticeContent)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seeMoreBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(noticeTitle)
                            .addGroup(pnlRoutineLayout.createSequentialGroup()
                                .addComponent(noticeTitle1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(effectiveDate)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 616, Short.MAX_VALUE)
                        .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        pnlRoutineLayout.setVerticalGroup(
            pnlRoutineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRoutineLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(noticeDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(pnlRoutineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRoutineLayout.createSequentialGroup()
                        .addComponent(noticeTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlRoutineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(noticeTitle1)
                            .addComponent(effectiveDate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlRoutineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(noticeContent)
                            .addComponent(seeMoreBtn))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRoutineLayout.createSequentialGroup()
                        .addGroup(pnlRoutineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRoutine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRoutine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void onEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onEditButtonActionPerformed
        // TODO add your handling code here:
        onEditClick.onTrigger();
    }//GEN-LAST:event_onEditButtonActionPerformed

    private void onDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onDeleteButtonActionPerformed
        // TODO add your handling code here:
        onDeleteClick.onTrigger();
    }//GEN-LAST:event_onDeleteButtonActionPerformed

    private void onSeeMoreBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onSeeMoreBtnActionPerformed
        // TODO add your handling code here:
        onSeeMoreClick.onTrigger();
    }//GEN-LAST:event_onSeeMoreBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel effectiveDate;
    private javax.swing.JLabel noticeContent;
    private javax.swing.JLabel noticeDate;
    private javax.swing.JLabel noticeTitle;
    private javax.swing.JLabel noticeTitle1;
    private javax.swing.JPanel pnlRoutine;
    private javax.swing.JButton seeMoreBtn;
    // End of variables declaration//GEN-END:variables
}
