/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vidyalaya.Components;

import java.util.logging.Level;
import java.util.logging.Logger;
import vidyalaya.DAO.ModuleDAO.ModuleDAOImplementation;
import vidyalaya.Model.RoutineData;
import vidyalaya.Utils.UIUtils;

/**
 *
 * @author trish
 */
public class RoutineCardUser extends javax.swing.JPanel {

    /**
     * Creates new form CourseCard1
     *
     * @param routine
     */
    public RoutineCardUser(RoutineData routine) {
        try {
            initComponents();
            courseTitle.setText(new ModuleDAOImplementation().getModuleByCode(routine.getModuleCode()).getName());
            details.setText(routine.getRoutineContent());
            weekday.setText(routine.getWeekday());

            UIUtils.setCustomFont(courseTitleHeader, 15f);
            UIUtils.setCustomFont(courseTitle, 17f);
            UIUtils.setCustomFont(detailsHeader, 15f);
            UIUtils.setCustomFont(weekday, 15f);
            UIUtils.setCustomFont(details, 17f);
        } catch (Exception ex) {
            Logger.getLogger(RoutineCardUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRoutine = new javax.swing.JPanel();
        courseTitleHeader = new javax.swing.JLabel();
        courseTitle = new javax.swing.JLabel();
        detailsHeader = new javax.swing.JLabel();
        details = new javax.swing.JLabel();
        weekday = new javax.swing.JLabel();

        pnlRoutine.setBackground(new java.awt.Color(255, 255, 255));
        pnlRoutine.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(222, 222, 222)));

        courseTitleHeader.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        courseTitleHeader.setForeground(new java.awt.Color(130, 130, 130));
        courseTitleHeader.setText("Course Title");

        courseTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        courseTitle.setText("Object Oriented Programming");

        detailsHeader.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        detailsHeader.setForeground(new java.awt.Color(130, 130, 130));
        detailsHeader.setText("Details");

        details.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        details.setText("12:00 PM - @LR-10 (3 hours)");

        weekday.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        weekday.setText("Sunday");

        javax.swing.GroupLayout pnlRoutineLayout = new javax.swing.GroupLayout(pnlRoutine);
        pnlRoutine.setLayout(pnlRoutineLayout);
        pnlRoutineLayout.setHorizontalGroup(
            pnlRoutineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRoutineLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(pnlRoutineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRoutineLayout.createSequentialGroup()
                        .addComponent(weekday)
                        .addContainerGap())
                    .addGroup(pnlRoutineLayout.createSequentialGroup()
                        .addGroup(pnlRoutineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(courseTitle)
                            .addComponent(courseTitleHeader))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 533, Short.MAX_VALUE)
                        .addGroup(pnlRoutineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(details)
                            .addComponent(detailsHeader)))))
        );
        pnlRoutineLayout.setVerticalGroup(
            pnlRoutineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRoutineLayout.createSequentialGroup()
                .addGroup(pnlRoutineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlRoutineLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(detailsHeader)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(details))
                    .addGroup(pnlRoutineLayout.createSequentialGroup()
                        .addComponent(weekday, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(courseTitleHeader)
                        .addGap(10, 10, 10)
                        .addComponent(courseTitle)))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRoutine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRoutine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel courseTitle;
    private javax.swing.JLabel courseTitleHeader;
    private javax.swing.JLabel details;
    private javax.swing.JLabel detailsHeader;
    private javax.swing.JPanel pnlRoutine;
    private javax.swing.JLabel weekday;
    // End of variables declaration//GEN-END:variables
}
