/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vidyalaya.Components;

import java.util.logging.Level;
import java.util.logging.Logger;

import vidyalaya.Utils.CallbackFn;
import vidyalaya.Utils.Utils;

import vidyalaya.Model.UserData;

/**
 *
 * @author trish
 */
public class UserCard extends javax.swing.JPanel {

    CallbackFn onEditClick, onDeleteClick;

    /**
     * Creates new form UserCard
     *
     * @param user
     * @param onEditClick
     * @param onDeleteClick
     */
    public UserCard(UserData user, CallbackFn onEditClick, CallbackFn onDeleteClick) {
        try {
            initComponents();
            userName.setText(user.getName());
            this.onEditClick = onEditClick;
            this.onDeleteClick = onDeleteClick;

            Utils.setCustomFont(courseTitleHeader, 15f);
            Utils.setCustomFont(userName, 17f);
        } catch (Exception ex) {
            Logger.getLogger(UserCard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlUser = new javax.swing.JPanel();
        courseTitleHeader = new javax.swing.JLabel();
        userName = new javax.swing.JLabel();
        editButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();

        pnlUser.setBackground(new java.awt.Color(255, 255, 255));
        pnlUser.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(222, 222, 222)));

        courseTitleHeader.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        courseTitleHeader.setForeground(new java.awt.Color(130, 130, 130));
        courseTitleHeader.setText("Full Name");

        userName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        userName.setText("Trishan Wagle");

        editButton.setBackground(new java.awt.Color(193, 241, 212));
        editButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vidyalaya/Assets/icons/Edit.png"))); // NOI18N
        editButton.setBorder(null);
        editButton.setBorderPainted(false);
        editButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editButton.setFocusPainted(false);
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onEditButtonActionPerformed(evt);
            }
        });

        deleteButton.setBackground(new java.awt.Color(234, 186, 184));
        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vidyalaya/Assets/icons/Delete.png"))); // NOI18N
        deleteButton.setBorder(null);
        deleteButton.setBorderPainted(false);
        deleteButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteButton.setFocusPainted(false);
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onDeleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlUserLayout = new javax.swing.GroupLayout(pnlUser);
        pnlUser.setLayout(pnlUserLayout);
        pnlUserLayout.setHorizontalGroup(
            pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUserLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUserLayout.createSequentialGroup()
                        .addComponent(courseTitleHeader)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(userName, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 196, Short.MAX_VALUE)
                .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlUserLayout.setVerticalGroup(
            pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUserLayout.createSequentialGroup()
                .addGap(0, 28, Short.MAX_VALUE)
                .addGroup(pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(editButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUserLayout.createSequentialGroup()
                        .addComponent(courseTitleHeader)
                        .addGap(10, 10, 10)
                        .addComponent(userName))
                    .addComponent(deleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void onEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onEditButtonActionPerformed
        // TODO add your handling code here:
        onEditClick.onTrigger();
    }//GEN-LAST:event_onEditButtonActionPerformed

    private void onDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onDeleteButtonActionPerformed
        // TODO add your handling code here:
        onDeleteClick.onTrigger();
    }//GEN-LAST:event_onDeleteButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel courseTitleHeader;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JPanel pnlUser;
    private javax.swing.JLabel userName;
    // End of variables declaration//GEN-END:variables
}
